SonicGarden/sgcop

rails/rubocop.yml
ruby/rubocop.yml
sgcop.gemspec
spec/spec_helper.rb

@maedana
最新版にあげてみました。
確認よろですー。

rubocop のバージョンを 0.45.0 にアップデート

---

rails/rubocop.yml
ruby/rubocop.yml

どうかな？？
ルール緩和の際はここで是非をディスカッションしたいっすね。

[review] ルール緩和

---

rails/rubocop.yml

feature specでどうしても長くなってしまうので制限不要かと

[review] RSpec/ExampleLengthの無効化

---

haml/haml-lint.yml
rails/rubocop.yml

もしかしたらdeviseのディレクトリも省いたらいいかもしれない

[review] kaminariのファイルで大量ヒットしてうっとおしいので

---

rails/rubocop.yml

https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/rails/reversible_migration.rb

Rails/ReversibleMigration が有効になるように

---

.rubocop.yml
README.md
exe/review-brakeman.sh
exe/review-eslint.sh
exe/review-rubocop.sh
lib/sgcop/version.rb
ruby/rubocop.yml
sgcop.gemspec

主な開発内容
* rubocop最新に
* 現在はopsworksでも問題ないのでbundler管理を推奨するように
* デフォルト設定見直し
* reviewdog最新に
* eslintの自動レビュー対応

[review] 0.0.29

---

exe/review-brakeman.sh
exe/sgcop
lib/sgcop/version.rb
rails/rubocop.yml
sgcop.gemspec

[review] 0.0.31

---

lib/sgcop/version.rb
ruby/rubocop.yml
sgcop.gemspec

[review] 0.0.36

---

lib/sgcop/version.rb
rails/rubocop.yml
ruby/rubocop.yml
sgcop.gemspec

[review] 0.2.6

---

lib/sgcop/version.rb
ruby/rubocop.yml
sgcop.gemspec

[review] 0.2.7

---

lib/sgcop/version.rb
rails/rubocop.yml
sgcop.gemspec

[review] 0.2.8

---

config/default.yml
lib/rubocop/cop/sgcop/capybara/matchers.rb
lib/rubocop/cop/sgcop/simple_format.rb
lib/rubocop/cop/sgcop/whenever.rb
lib/sgcop/version.rb
rails/rubocop.yml
sgcop.gemspec

[review] 0.3.0

---

lib/sgcop/version.rb
rails/rubocop.yml
ruby/rubocop.yml
sgcop.gemspec

- rubocop@1.4.1
- rubocop-performance@1.9.0

[review] 0.3.4

---

lib/sgcop/version.rb
rails/rubocop.yml

schema.rbだけだとmulti-dbのときにignore出来ないので、multi-dbで生成される全てのschema.rbをignoreしたい。

[review] chore: multi-dbを利用したのときの*schema.rb全てをignoreしたい

---

lib/sgcop/version.rb
ruby/rubocop.yml
sgcop.gemspec

[review] 0.3.10

---

.rubocop.yml
config/default.yml
lib/rubocop/cop/sgcop/simple_form_association.rb
lib/sgcop.rb
lib/sgcop/version.rb
spec/rubocop/cop/sgcop/simple_form_association_spec.rb

collection オプションを指定しない association メソッドの使用を警告するよう修正

[review] simple_form の association メソッドの使用に関する警告

---

lib/sgcop/version.rb
rails/rubocop.yml
ruby/rubocop.yml
sgcop.gemspec

[review] 0.4.2

---

lib/sgcop/version.rb
rails/rubocop.yml
sgcop.gemspec

[review] 0.4.4

---

lib/sgcop/version.rb
rails/rubocop.yml
sgcop.gemspec

[review] 0.4.7

---

lib/sgcop/version.rb
sgcop.gemspec

[review] 0.4.8

---

lib/sgcop/version.rb
rails/rubocop.yml
sgcop.gemspec

[review] 0.4.9

---

lib/sgcop/version.rb
ruby/rubocop.yml
sgcop.gemspec

[review] 0.4.11

---

lib/sgcop/version.rb
rails/rubocop.yml
sgcop.gemspec

[review] 0.5.1

---

lib/sgcop/version.rb
sgcop.gemspec

[review] 0.5.2

---

lib/sgcop/version.rb
rails/rubocop.yml
sgcop.gemspec

[review] 0.5.6

---

lib/sgcop/version.rb
rails/rubocop.yml
sgcop.gemspec

- rubocop-rspec@2.10.0
- チェック対象からの除外ファイル追加

[review] 0.5.8

---

lib/sgcop/version.rb
rails/rubocop.yml
sgcop.gemspec

[review] 0.5.12

---

lib/sgcop/version.rb
sgcop.gemspec

[review] 依存からhaml_lint削除

---

lib/sgcop/version.rb
ruby/rubocop.yml

[review] 0.7.2

---

rails/rubocop.yml
ruby/rubocop.yml
sgcop.gemspec

- rubocop@v1.37.0
- rubocop-rails@v2.17.0
- rubocop-rspec@v2.14.0

[review] Update dependency

---

.github/dependabot.yml
.github/workflows/rspec.yml
lib/sgcop/version.rb
ruby/rubocop.yml
sgcop.gemspec
spec/rubocop/cop/sgcop/capybara/sleep_spec.rb
spec/rubocop/cop/sgcop/link_to_ujs_options_spec.rb
spec/rubocop/cop/sgcop/request_remote_ip_spec.rb
spec/rubocop/cop/sgcop/simple_form_association_spec.rb
spec/rubocop/cop/sgcop/simple_format_spec.rb
spec/rubocop/cop/sgcop/unscoped_spec.rb
spec/rubocop/cop/sgcop/whenever_spec.rb

- rubocop@1.49.0
- Add CI settings
- Fix test

[review] 0.8.5

---

lib/sgcop/version.rb
sgcop.gemspec

[review] 0.10.16

---

rails/rubocop.yml

Revert "[review] fix: RSpecRails -> RSpec/Rails"

---

lib/rubocop/cop/sgcop/resource_action_order.rb

対象ファイルは設定ファイルで絞っているので不要だった処理を削除

[review] Remove routes_file? check from ResourceActionOrder cop
